### ISSUE TITLE
Wiki editing not open for public yet

### ISSUE THREAD

**Issue by xytaz** [fabfoundation/mods#20]
@TheBeachLab Hi. It seems the wiki is not open for pubic editing by default (https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis).

Please let me know if you prefer to enable it or have the documentation pushed into the repo itself.

Thanks.

**Comment by TheBeachLab** [comment]
Thanks for noticing! think I fixed this now

**Comment by xytaz** [comment]
@TheBeachLab Thanks for the quick response! All good now.
