### ISSUE TITLE
hotkeys in colemak keyboard not working

### ISSUE THREAD

**Issue by TheBeachLab** [fabfoundation/mods#29]
I have a colemak keyboard layout and supposedly `CONTROL + ALT + D` activates dark mode. But in my keyboard it activates with the `S` key (which is where the `D` is located in a qwerty keyboard), instead of the colemak `D` key.  Strange.

**Comment by s-ol** [comment]
IIRC there are different properties on Keyboard events - `.key` and `.keyCode` etc; If you have your colemak layout set up in software rather than firmware then maybe these two don't correspond in the same way mods expects them to

**Comment by TheBeachLab** [comment]
So true :facepalm: my colimak comes from 

`setxkbmap -layout us -variant colemak`

and from mods.js we use `.code`

```
    //
    // Toggle Dark Mode 'Ctrl+Alt+d'
    //
    window.addEventListener('keydown', function(evt) {
        if (evt.code == 'KeyD' && evt.ctrlKey && evt.altKey) {
```

From https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent the `.code` property raises this warning

> Warning: This ignores the user's keyboard layout, so that if the user presses the key at the "Y" position in a QWERTY keyboard layout (near the middle of the row above the home row), this will always return "KeyY", even if the user has a QWERTZ keyboard (which would mean the user expects a "Z" and all the other properties would indicate a "Z") or a Dvorak keyboard layout (where the user would expect an "F").

Using `.key` fixed it, thanks!
